<?php

/**
 * @file
 * eDidaktikum module.
 */

/**
 * Implements hook_menu().
 */
function edidaktikum_menu() {
  $items['home'] = array(
    'title' => 'Home',
    'page callback' => 'edidaktikum_home_page',
    'access callback' => TRUE,
    'weight' => 0,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * eDidaktikum home page.
 */
function edidaktikum_home_page() {
  drupal_set_title('');
  $content['preface'] = array(
    '#type' => 'item',
    '#markup' => '<h2>' . t('Latest content') .'</h2>',
  );

  if (module_exists('ed_news')) {
    $latest_news = ed_news_get_latest_news();
    if (!empty($latest_news)) {
      $content['latest-news'] = node_view($latest_news, 'teaser');
    }
  }

  if (module_exists('ed_event')) {
    $latest_event = ed_event_get_latest_event();
    if (!empty($latest_event)) {
      $content['latest-event'] = node_view($latest_event, 'teaser');
    }
  }

  return $content;
}

function edidaktikum_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['featured'] = array(
    'label' => t('Featured'),
    'custom settings' => TRUE,  
  );
}

function edidaktikum_preprocess_node(&$vars) {
  if ($vars['view_mode'] == 'featured') {
    $vars['theme_hook_suggestions'][] = 'node__featured';
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__featured';
  }
}

