<?php

/**
 * @file
 * eDidaktikum portfolio module.
 */

/**
 * Implements hook_menu().
 */
function ed_portfolio_menu() {
  $items['dashboard/portfolio'] = array(
    'title' => t('Portfolio'),
    'page callback' => 'ed_portfolio_listing_page',
    'access callback' => 'user_is_logged_in',
    'weight' => 5,
    'menu_name' => 'ed-dashboard-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['portfolio/%'] = array(
    'page callback' => 'ed_portfolio_page',
    'page arguments' => array(1),  
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Portfolios listing page.
 */

function ed_portfolio_listing_page(){
  menu_tree_set_path('main-menu', 'dashboard');
  //drupal_add_css('ul.links.inline {display: none;}', array('group' => CSS_THEME, 'type' => 'inline'));
  $content = array();
  $content['add-new-portfolio'] = array(
    '#type' => 'link',
    '#title' => t('Add new portfolio'),
    '#href' => 'node/add/ed-portfolio',
  );
  $table_type = 'pager-table';
  $user_portfolio_ids = ed_portfolio_get_user_portfolios();
  $nodes = node_load_multiple($user_portfolio_ids);
  $rows = array();
  foreach($nodes as $node){
    if($node->status=='1'){
      $status = '<span class="pub-portfolio">'.t('Public').'</span>';
    }else if($node->status=='0'){
      $status = '<span class="priv-portfolio">'.t('Private').'</span>';
    }else{
      $status = t('error');
    }
    $rows[] = array(
      'data' => array(
        'status' => $status,
        'title' => l($node->title, 'node/'.$node->nid),
        'created' => format_date($node->created, 'custom', 'd/m/Y'),
      ),
    );
  }
  $content[$table_type] = array(
    '#theme' => 'table',
    '#rows' => $rows,
    '#header' => array(t('Status'), t('Title'), t('Date')),
  );
  $content['pager'] = array('#theme' => 'pager');
  
  drupal_add_css('span.pub-portfolio {color:green;}', array('group' => CSS_THEME, 'type' => 'inline'));
  drupal_add_css('span.priv-portfolio {color:red;}', array('group' => CSS_THEME, 'type' => 'inline'));
  
  
  return $content;
}

/**
 * User portfolio ids.
 */
function ed_portfolio_get_user_portfolios() {
  global $user;
  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.type', 'ed_portfolio')
    ->condition('n.uid', $user->uid)
    ->addTag('node_access')
    ->range()
    ->orderBy('n.created', 'DESC');
  $nids = $query->execute()->fetchCol();
  return $nids;
}

function ed_portfolio_page($portfolio_id) {
  $portfolio = node_load($portfolio_id);
  if ($portfolio && $portfolio->type == 'ed_portfolio') {
    echo theme('ed_portfolio_page', array('node_view' => node_view($portfolio, 'entity_view')));
    return NULL;
  }
  return array();
}

function ed_portfolio_theme($existing, $type, $theme, $path) {
  return array(
    'ed_portfolio_page' => array(
      'variables' => array('node_view' => '', 'site_name' => variable_get('site_name', 'Drupal'), 'front_page' => variable_get('site_frontpage')),
      'template' => 'ed_portfolio_page',
      'path' => drupal_get_path('module', 'ed_portfolio'),
      'render element' => 'element',
    ), 
  );  
}

/**
 * Implements hook_ctools_plugin_api().
 */
function ed_portfolio_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_field_widget_info().
 */
/*function ed_portfolio_field_widget_info() {
  $widgets['ed_portfolio_items'] = array(
    'label' => t('Portfolio items'),
    'description' => t('Widget for drag and drop.'),
    'field types' => array('entityreference'),
  );

  return $widgets;
}*/

/**
 * Implements hook_views_api().
 */
function ed_portfolio_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'ed_portfolio') . '/includes/views',
  );
}

