<?php

require_once('ed_page_functions.inc');

/*
 * Implements hook_info().
 */

function ed_page_node_info() {
  $items['ed_page'] = array(
    'name' => t('Page'),
    'type' => 'ed_page',
    'base' => 'node_content',
    'description' => t('description'),
    'has_title' => '1',
    'title_label' => t('Title'),
    'body_label' => t('body_label'),
  );
  return $items;
}

/*
 * Implements hook_form().
 */
function ed_page_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_form_alter().
 */
function ed_page_form_alter(&$form, &$form_state, $form_id) {
  if ('ed_page_node_form' == $form_id) {
    if (empty($form['#node']->nid)) {
      drupal_set_title(t('Create Page'));
    }
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function ed_page_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
}

