<?php

require_once('ed_learning_resource_functions.inc');

/*
 * Implements hook_info().
 */
function ed_learning_resource_node_info() {
  $items['ed_learning_resource'] = array(
    'name' => t('Learning Resource'),
	  'type' => 'ed_learning_resource',
	  'base' => 'node_content',
	  'description' => t('Description'),
	  'has_title' => '1',
	  'title_label' => t('Title'),
	  'body_label' => t('body_label'),

  );
  return $items;
}

/*
 * Implements hook_form().
 */
function ed_learning_resource_form($node, $form_state) {
  return node_content_form($node, $form_state);
}


/*
 * Implements hook_menu().
 */


function ed_learning_resource_menu() {

  $items['resources'] = array(
    'title' => t('Resources'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ed_learning_resource_dynamic_sections'),
    'access callback' => TRUE,
    'weight' => 15,
    'file' => 'ed_learning_resource_ajax.inc',
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function ed_learning_resource_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  error_log($module. " " . $api);
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
}
