<?php

/**
 * @file
 * News module.
 */

/**
 * Implements hook_menu().
 */
function ed_news_menu() {
  $items['news'] = array(
    'title' => 'News',
    'page callback' => 'ed_news_listing_page',
    'access callback' => TRUE,
    'file' => 'ed_news.pages.inc',
    'weight' => 5,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Loads latest public ed_news node.
 *
 * @return
 *   A fully loaded ed_news node or FALSE.
 */
function ed_news_get_latest_news() {
  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.status', 1)
    ->condition('n.type', 'ed_news')
    ->addTag('node_access')
    ->range(0, 1)
    ->orderBy('n.created', 'DESC');

  $nids = $query->execute()->fetchCol();

  if (!empty($nids)) {
    return node_load($nids[0]);
  }

  return FALSE;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function ed_news_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

