<?php

/**
 * @file
 * News module.
 */

/**
 * Implements hook_menu().
 */
function ed_news_menu() {
  $items['news'] = array(
    'title' => 'News',
    'page callback' => 'ed_news_listing_page',
    'access callback' => TRUE,
    'file' => 'ed_news.pages.inc',
    'weight' => 5,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['news/rss'] = array(
    'title' => 'News',
    'page callback' => 'ed_news_latest_feed',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Latest news RSS page.
 */
function ed_news_latest_feed() {
  $nids = db_select('node', 'n')
    ->fields('n', array('nid', 'created'))
    ->condition('type', 'ed_news')
    ->condition('status', 1)
    ->orderBy('created', 'DESC')
    ->range(0, variable_get('feed_default_items', 10))
    ->addTag('node_access')
    ->execute()
    ->fetchCol();

  $channel['title'] = t('!site_name news', array('!site_name' => variable_get('site_name', 'eDidaktikum')));
  $channel['link'] = url('news/rss', array('absolute' => TRUE));

  node_feed($nids, $channel);
}

/**
 * Loads latest public ed_news node.
 *
 * @return
 *   A fully loaded ed_news node or FALSE.
 */
function ed_news_get_latest_news() {
  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.status', 1)
    ->condition('n.type', 'ed_news')
    ->addTag('node_access')
    ->range(0, 1)
    ->orderBy('n.created', 'DESC');

  $nids = $query->execute()->fetchCol();

  if (!empty($nids)) {
    return node_load($nids[0]);
  }

  return FALSE;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function ed_news_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_preprocess_node().
 */
function ed_news_preprocess_node(&$vars) {
  if (isset($vars['front']) && $vars['front'] == TRUE && $vars['node']->type == 'ed_news') {
    $vars['user_picture'] = '';
    $vars['submitted'] = format_date($vars['node']->created, 'short');
  }
}

/**
 * Implements hook_form_alter().
 */
function ed_news_form_alter(&$form, &$form_state, $form_id) {
  if ('ed_news_node_form' == $form_id) {
    if (empty($form['#node']->nid)) {
      drupal_set_title(t('Create News'));
    }
  }
}

