<?php


/**
 * Implements hook_node_info().
 */

function ed_subgroup_node_info(){
  $items['ed_subgroup'] = array(
    'name' => t('Subgroup'),
    'type' => 'ed_subgroup',
    'base' => 'node_content',
    'description' => t('description'),
    'has_title' => '1',
    'title_label' => t('Title'),
    'body_label' => t('body_label'),
  );
  return $items;
}


function ed_subgroup_resource_form($node, $form_state){
  return node_content_form($node, $form_state);
}


/**
 * Implements hook_ctools_plugin_api().
 */
function ed_subgroup_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

//XXX This overrides ed_cluster_menu
//function ed_subgroup_menu(){
//  $items['node/%node/news'] = array(
//    'title' => 'News',
//    'page callback' => 'ed_listing_from_group',
//    'access callback' => 'ed_subgroup_content_listing_access',
//    'page arguments' => array('node', 1, 'ed_news'),
//    'access arguments' => array('node', 1, 'ed_news'),
//    'type' => MENU_LOCAL_TASK,
//    'weight' => 50,
//  );
//  $items['node/%node/task-manager'] = array(
//    'title' => 'Task Manager',
//    'page callback' => 'ed_task_manager',
//    'access callback' => 'ed_task_manager_access',
//    'page arguments' => array('node', 1),
//    'access arguments' => array('node', 1),
//    'type' => MENU_LOCAL_TASK,
//    'weight' => 50,
//  );
//  $items['node/%node/event'] = array(
//    'title' => 'Events',
//    'page callback' => 'ed_listing_from_group',
//    'access callback' => 'ed_subgroup_content_listing_access',
//    'page arguments' => array('node', 1, 'ed_event'),
//    'access arguments' => array('node', 1, 'ed_event'),
//    'type' => MENU_LOCAL_TASK,
//    'weight' => 50,
//  );
//  $items['node/%node/blog'] = array(
//    'title' => 'Posts',
//    'page callback' => 'ed_listing_from_group',
//    'access callback' => 'ed_subgroup_content_listing_access',
//    'page arguments' => array('node', 1, 'ed_blog'),
//    'access arguments' => array('node', 1, 'ed_blog'),
//    'type' => MENU_LOCAL_TASK,
//    'weight' => 50,
//  );
//  $items['node/%node/learning-resource'] = array(
//    'title' => 'Learning Resources',
//    'page callback' => 'ed_listing_from_group',
//    'access callback' => 'ed_subgroup_content_listing_access',
//    'page arguments' => array('node', 1, 'ed_learning_resource'),
//    'access arguments' => array('node', 1, 'ed_learning_resource'),
//    'type' => MENU_LOCAL_TASK,
//    'weight' => 50,
//  );
//  $items['node/%node/forum'] = array(
//    'title' => 'Discussion Board',
//    'page callback' => 'ed_listing_from_group',
//    'access callback' => 'ed_subgroup_content_listing_access',
//    'page arguments' => array('node', 1, 'ed_forum'),
//    'access arguments' => array('node', 1, 'ed_forum'),
//    'type' => MENU_LOCAL_TASK,
//    'weight' => 50,
//  );
//
//  $items['node/%node/bookmark'] = array(
//    'title' => 'Bookmarks',
//    'page callback' => 'ed_listing_from_group',
//    'access callback' => 'ed_subgroup_content_listing_access',
//    'page arguments' => array('node', 1, 'ed_bookmark'),
//    'access arguments' => array('node', 1, 'ed_bookmark'),
//    'type' => MENU_LOCAL_TASK,
//    'weight' => 50,
//  );
//  $items['node/%node/file'] = array(
//    'title' => 'Files',
//    'page callback' => 'ed_listing_from_group',
//    'access callback' => 'ed_subgroup_content_listing_access',
//    'page arguments' => array('node', 1, 'ed_file'),
//    'access arguments' => array('node', 1, 'ed_file'),
//    'type' => MENU_LOCAL_TASK,
//    'weight' => 50,
//  );
//
//  return $items;
//}

function ed_subgroup_content_listing_access($filler, $gnode, $type){
  $is_group = _ed_is_nid_subgroup($gnode->nid);
  return $is_group;
}

function _ed_is_nid_subgroup($nid){
  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.type', array('ed_subgroup', 'ed_cluster'), 'IN')
    ->condition('n.nid', $nid);
  $nids = $query->execute()->fetchCol();
  if(!empty($nids)){
    return true;
  }
  return false;
}


function ed_subgroup_node_insert($node){
  if($node->type == 'ed_subgroup'){
    $subgroupnode = node_load($node->nid);

    $parentgroupnode = node_load($subgroupnode->og_group_ref[LANGUAGE_NONE][0]['target_id']);
    $parentgroupadmins = _ed_cluster_get_group_admins($parentgroupnode, true);

    foreach($parentgroupadmins as $parentgroupadmin){

      $values = array(
        'entity_type' => 'user',
        'entity' => $parentgroupadmin,
        'field_name' => FALSE,
        'state' => OG_STATE_ACTIVE,
      );
      og_group('node', $subgroupnode->nid, $values);
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function ed_subgroup_ctools_plugin_directory($module, $plugin) {
  if(('content_types' == $plugin && 'ctools' == $module)) {
    return 'plugins/' . $plugin;
  }
}
