<?php

/**
 * @file
 * Event module.
 */

/**
 * Implements hook_menu().
 */
function ed_event_menu() {
  $items['events'] = array(
    'title' => t('Events'),
    'page callback' => 'ed_event_listing_page',
    'access callback' => TRUE,
    'weight' => 10,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Events listing page.
 */
function ed_event_listing_page() {
  $content = array();
  
  $latest = ed_event_get_latest_event();
  if (!empty($latest)) {
    $content['latest-event'] = node_view($latest, 'teaser');
  } 

  $upcoming_events = ed_event_get_upcoming_events($latest);

  if (!empty($upcoming_events)) {
    $content['upcoming-events-heading'] = array(
      '#type' => 'markup',
      '#markup' => '<h2>' . t('Upcoming events') . '</h2>',
    );
    $nodes = node_load_multiple($upcoming_events);
    $build = node_view_multiple($nodes);
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
    $content['upcoming-events'] = $build;
  }


  return $content;
}

/**
 * Latest event.
 */
function ed_event_get_latest_event() {
  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.status', 1)
    ->condition('n.type', 'ed_event')
    ->addTag('node_access')
    ->range(0, 1)
    ->orderBy('n.created', 'DESC');

  $nids = $query->execute()->fetchCol();
  
  if (!empty($nids)) {
    return node_load($nids[0]);
  }

  return FALSE;
}

/**
 * Upcoming events.
 */
function ed_event_get_upcoming_events($exclude_event) {
  $query = db_select('node', 'n')
    ->extend('PagerDefault')
    ->fields('n', array('nid'))
    ->condition('n.status', 1)
    ->condition('n.type', 'ed_event')
    ->addTag('node_access')
    ->limit(3);

  $query->leftJoin('field_data_ed_event_field_end', 'end', 'n.nid = end.entity_id');
  $query->condition('end.ed_event_field_end_value', time(), '>');
  $query->orderBy('end.ed_event_field_end_value', 'ASC');


  if (!empty($exclude_event)) {
    $query->condition('n.nid', $exclude_event->nid, '<>');
  }
  
  $nids = $query->execute()->fetchCol();
 
  return $nids;
}

