<?php

/**
 * @file
 * eDidaktikum dashboard module.
 */

/**
 * Implements hook_menu().
 */
function ed_dashboard_menu() {
  $items['dashboard'] = array(
    'title' => t('Dashboard'),
    'page callback' => 'ed_dashboard_page',
    'access callback' => 'user_is_logged_in',
    'weight' => -5,
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['dashboard/home'] = array(
    'title' => t('Dashboard'),
    'page callback' => 'ed_dashboard_page',
    'access callback' => 'user_is_logged_in',
    'weight' => 0,
    'menu_name' => 'ed-dashboard-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['dashboard/drafts'] = array(
    'title' => t('Drafts'),
    'page callback' => 'ed_dashboard_drafts_page',
    'access callback' => 'user_is_logged_in',
    'weight' => 30,
    'menu_name' => 'ed-dashboard-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['dashboard/discover'] = array(
    'title' => t('Discover'),
    'page callback' => 'drupal_get_form',
    'access callback' => 'user_is_logged_in',
    'page arguments' => array('ed_dashboard_discover_page', 2),
    'weight' => 40,
    'menu_name' => 'ed-dashboard-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['dashboard/search/delete/%'] = array(
    'page callback' => 'ed_dashboard_delete_search',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access callback' => 'user_is_logged_in',
  );
  $items['dashboard/student_activity'] = [
    'title' => t('Student activity'),
    'access callback' => 'ed_current_user_is_administrator',
    'page callback' => 'ed_student_activity_page',
    'weight' => 50,
    'menu_name' => 'ed-dashboard-menu',
    'type' => MENU_NORMAL_ITEM
  ];

  return $items;
}

function ed_current_user_is_administrator() {
  return in_array('administrator', $GLOBALS['user']->roles);
}

function ed_student_activity_page() {
  menu_tree_set_path('main-menu', 'dashboard');

  //  _fetch og role names_
  $q = db_select('og_role', 'ogr');
  $q->fields('ogr', ['rid', 'name']);
  $tmp = $q->execute()->fetchAll(PDO::FETCH_ASSOC);
  $og_role_names_by_id = [];
  foreach ($tmp as $role) $og_role_names_by_id[$role['rid']] = $role['name']; 
  unset($q, $tmp);

  //  _fetch all users_
  //  basic
  $q = db_select('users', 'u'); 
  $q->condition('u.status', 1); 
  $q->fields('u', ['uid', 'data']);

  //  groups
  $q->join('og_membership', 'ogm', 'ogm.etid = u.uid AND ogm.entity_type = \'user\' AND ogm.state = 1');
  $q->addField('ogm', 'gid', 'group_ids');

  //  group creation
  $q->leftJoin('node', 'n', 'n.nid = ogm.gid AND n.type = \'ed_cluster\' AND n.uid = u.uid');
  $q->addField('n', 'nid', 'created_group_ids');

  //  group roles
  $q->leftJoin('og_users_roles', 'ogur', 'ogur.uid = u.uid');
  $q->addField('ogur', 'gid', 'group_role_group_id');
  $q->addField('ogur', 'rid', 'group_role_id');

  //  names
  $q->leftJoin('field_data_ed_field_full_name', 'fn', 'fn.entity_id = u.uid');
  $q->addField('fn', 'ed_field_full_name_value', 'full_name');
  
  //  study groups
  $q->leftJoin('field_data_ed_field_study_group', 'sg', 'sg.entity_id = u.uid');
  $q->addField('sg', 'ed_field_study_group_value', 'study_group_ids');

  //  role ids
  $q->leftJoin('users_roles', 'ur', 'ur.uid = u.uid');
  $q->addField('ur', 'rid', 'role_ids');

  //  roles
  $q->leftJoin('role', 'r', 'r.rid = ur.rid');
  $q->addField('r', 'name', 'role_names');

  //  exec
  $users = $q->execute()->fetchAll(PDO::FETCH_ASSOC);
  unset($q);

  //  concentrate
  $c_users = [];
  foreach ($users as $user) {
    if (!isset($c_users[$user['uid']])) {
      //  prep
      $c_user = $user;
      $c_user['study_group_ids'] = [];
      $c_user['role_names'] = [];
      $c_user['role_ids'] = [];
      $c_user['group_ids'] = [];
      $c_user['created_group_ids'] = [];
      $c_user['group_role_ids_by_group_id'] = [];
      $c_user['group_role_names_by_group_id'] = [];
      unset($c_user['group_role_group_id'], $c_user['group_role_id']);
      $c_users[$user['uid']] =& $c_user;
      unset($c_user);
    }

    //  fill
    $c_user =& $c_users[$user['uid']];

    if (!empty($user['study_group_ids']) && !in_array($user['study_group_ids'], $c_user['study_group_ids'])) $c_user['study_group_ids'] []= $user['study_group_ids'];
    if (!empty($user['role_ids']) && !in_array($user['role_ids'], $c_user['role_ids'])) $c_user['role_ids'] []= $user['role_ids'];
    if (!empty($user['role_names']) && !in_array($user['role_names'], $c_user['role_names'])) $c_user['role_names'] []= $user['role_names'];
    if (!empty($user['group_ids']) && !in_array($user['group_ids'], $c_user['group_ids'])) $c_user['group_ids'] []= $user['group_ids'];
    if (!empty($user['created_group_ids']) && !in_array($user['created_group_ids'], $c_user['created_group_ids'])) $c_user['created_group_ids'] []= $user['created_group_ids'];

    if (!empty($user['group_role_id']) && !empty($user['group_role_group_id'])) {
      if (!isset($c_user['group_role_ids_by_group_id'][$user['group_role_group_id']])) {
        $c_user['group_role_ids_by_group_id'][$user['group_role_group_id']] = [];
        $c_user['group_role_names_by_group_id'][$user['group_role_group_id']] = [];
      }

      if (!in_array($user['group_role_id'], $c_user['group_role_ids_by_group_id'][$user['group_role_group_id']])) {
        $c_user['group_role_ids_by_group_id'][$user['group_role_group_id']] []= $user['group_role_id'];
        $c_user['group_role_names_by_group_id'][$user['group_role_group_id']] []= $og_role_names_by_id[$user['group_role_id']];
      }
    }

    unset($user, $c_user);
  }
  $users = $c_users;

  //  hybridauth names
  foreach ($users as &$user) {
    if ($user['full_name'] === NULL) {
      $data = unserialize($user['data']);
      if (isset($data['hybridauth']) && isset($data['hybridauth']['displayName'])) {
        $user['full_name'] = $data['hybridauth']['displayName'];
      }
    }
    unset($user);
  }

  //  _group admins by group ids
  $group_admins_by_group_ids = [];

  foreach ($users as $user) {
    $administrating = $user['created_group_ids'];
    foreach ($user['group_role_names_by_group_id'] as $group_id => $group_roles) {
      if (in_array(OG_ADMINISTRATOR_ROLE, $group_roles)) {
        $administrating []= $group_id;
      }
    }

    foreach ($administrating as $gid) {
      if(!isset($group_admins_by_group_ids[$gid])) $group_admins_by_group_ids[$gid] = [];
      $group_admins_by_group_ids[$gid] []= ['uid' => $user['uid'], 'roles' => [OG_ADMINISTRATOR_ROLE]];
    }
    unset($user);
  }

  //  _fetching all tasks_
  //  basic
  $q = db_select('og_membership', 'ogm');
  $q->condition('ogm.entity_type', 'node');
  $q->fields('ogm', ['gid']);
  $q->join('node', 'n', 'n.nid = ogm.etid AND n.type = \'ed_task\' AND n.status = 1');
  $q->fields('n', ['nid', 'title']);

  //  due date
  $q->join('field_data_ed_task_due_date', 'dd', 'dd.entity_id = ogm.etid');
  $q->addField('dd', 'ed_task_due_date_value', 'due_date');

  //  study groups
  $q->leftJoin('field_data_ed_task_field_study_group', 'sg', 'sg.entity_id = ogm.etid');
  $q->addField('sg', 'ed_task_field_study_group_value', 'study_group_ids');

  //  targeted members
  $q->leftJoin('field_data_ed_field_to_group_member', 'tm', 'tm.entity_id = ogm.etid');
  $q->addField('tm', 'ed_field_to_group_member_target_id', 'targeted_member_ids');

  //  exec
  $tasks = $q->execute()->fetchAll(PDO::FETCH_ASSOC);
  unset($q);

  //  rename and concentrate
  $tasks = ed_util_array_concentrate_members($tasks, 'nid', ['study_group_ids', 'targeted_member_ids']);

  //  _sort tasks by gid_
  $tasks_by_gid = [];
  foreach ($tasks as &$task) {
    $gid = $task['gid'];
    if (!isset($tasks_by_gid[$gid])) $tasks_by_gid[$gid] = [];
    $tasks_by_gid[$gid] []=& $task;
    unset($task);
  }


  //  _match tasks to users_
  
  foreach ($users as &$user) {
    $user['answers'] = [];
    $user['unanswered'] = 0;
    $user['accepted'] = 0;
    $user['unchecked'] = 0;
    $user['rejected'] = 0;
    $user['total_grade'] = 0;
    $user['total_gradeables'] = 0;
    $user['on_time'] = 0;

    foreach($user['group_ids'] as $gid) {
      if (!isset($tasks_by_gid[$gid])) continue;
      foreach($tasks_by_gid[$gid] as $task) {
        $applicable = true;
        if (count($task['study_group_ids']) > 0) {
          $applicable = false;
          foreach ($task['study_group_ids'] as $sg_id) {
            if (in_array($sg_id, $user['study_group_ids'])) $applicable = true;
          }
        }
        if (in_array($user['uid'], $task['targeted_member_ids'])) $applicable = true;
        if (in_array($gid, $user['created_group_ids'])) $applicable = false;
        if (isset($user['group_role_names_by_group_id'][$gid]) && in_array(OG_ADMINISTRATOR_ROLE, $user['group_role_names_by_group_id'][$gid])) $applicable = false;

        if ($applicable && isset($group_admins_by_group_ids[$gid])) {
          $answer = ed_get_answer($task['nid'], $user['uid'], false, $group_admins_by_group_ids[$gid]);
          $user['answers'][$task['nid']] = $answer;
          $user[$answer['status']]++;
          if (isset($answer['grade'])) {
            $user['total_grade'] += $answer['grade'];
            $user['total_gradeables']++;
          }
          if (isset($answer['created'])) {
            if ($answer['created'] < $task['due_date']) $user['on_time']++;
          }
        }
      }
      unset($gid);
    }
    unset($user);
  }


  //  _process_
  $table = "<table><tr><th>Nimi</th><th>Aktiivsus skoor</th></tr>";

  foreach($users as &$user) {
    if (count($user['answers']) > 0) {
      $score1 = $user['accepted'] / (count($user['answers']) - $user['unchecked']);
      $score2 = $user['total_gradeables'] < 1 ? 1 : ($user['total_grade'] / $user['total_gradeables']) / 100;
      $score3 = $user['on_time'] / count($user['answers']);
      $score = ($score1 + $score2 + $score3) / 3 * 100;
      $table .= "<tr><td>" . $user['full_name'] . "</td><td>" . $score . "</td></tr>"; 
    }

    unset($user);
  }
  $table .= "</table>";
    


  $content = [];
  return $table;
}

/**
 * Dashboard page.
 */
function ed_dashboard_page() {
  menu_tree_set_path('main-menu', 'dashboard');
 
  $content = array();

  $group_nids = _ed_dashboard_get_current_user_groups();
  if (!empty($group_nids)) {
    $groups = node_load_multiple($group_nids);
  }

  if (!empty($groups)) {
    $content['groups-listing'] = node_view_multiple($groups, 'dashboard');
	
	
    foreach ($content['groups-listing']['nodes'] as $node){
      if (isset($node['#node']->picture)) {
        //Hide user picture
        $node['#node']->picture = ['#printed' => false];
      }
    }
    $content['groups-listing']['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
	
  } else {
    $content['groups-not-found'] = array(
      '#type' => 'markup',
      '#prefix' => '<div class="ed-message ed-message-notice">',
      '#markup' => t('Hi! Nothing to show here at the moment. Join some group to see latest updates from it.'),
      '#suffix' => '</div>',
    );
  }

  return $content; 
}

/**
 * Dashboard drafts page.
 */
function ed_dashboard_drafts_page() {
  menu_tree_set_path('main-menu', 'dashboard');

  $account = $GLOBALS['user'];
  $content = array();

  // Get all user drafts
  $query = db_select('node', 'n')
    ->extend('PagerDefault')
    ->fields('n', array('nid'))
    ->condition('n.status', 0)
    ->condition('n.uid', $account->uid)
    ->limit(ed_get_paging_nr())
    ->orderBy('n.created', 'DESC');

  $nids = $query->execute()->fetchCol();

  if (!empty($nids)) {
    $nodes = node_load_multiple($nids);
    $build = node_view_multiple($nodes);
    $build['pager'] = array(
      '#theme' => 'pager',
      '#weight' => 5,
    );
    $content['drafts-listing'] = $build;
  }

  return $content;
}

/**
 * Dashboard discover page.
 */
function ed_dashboard_discover_page($form, &$form_state, $tag = '') {
  menu_tree_set_path('main-menu', 'dashboard');

  $form['search_tag'] = array(
    '#type' => 'textfield',
    '#title' => t('Search tag'),
    '#default_value' => $tag,
    '#size' => 60,
    '#maxlength' => 128,
  );

  $form['buttons']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#name' => 'op-search',
  );

  if (!empty($tag)) {
    $term = taxonomy_get_term_by_name($tag, 'tags');

    if ($term) {
      $form['buttons']['submit-save-search'] = array(
        '#type' => 'submit',
        '#value' => t('Save Search'),
        '#name' => 'op-save-search',
        '#attributes' => array(
          'class' => array('btn-link'),
        ),
      );

      $term = array_shift($term);

      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')
        ->propertyCondition('status', 1)
        ->fieldCondition('field_tags', 'tid', $term->tid, '=')
        ->pager(ed_get_paging_nr());

      $result = $query->execute();
      if (isset($result['node'])) {
        $nids = array_keys($result['node']);
        $nodes = node_load_multiple($nids);

        if($nodes) {
          foreach ($nodes as $node) {
            $user = user_load($node->uid);

            $rows []= array(
              'data' => t('@node_type_name !node by !user', array(
                '@node_type_name' => edidaktikum_get_node_type_name($node->type, TRUE),
                '!node' => l(edidaktikum_get_node_title($node), 'node/' . $node->nid),
                '!user' => l(edidaktikum_get_full_name_for_user_account($user), 'user/' . $user->uid)
              )),
            );
          }
          $form['result-listing']['list'] = array(
            '#theme' => 'item_list',
            '#type' => 'ul',
            '#attributes' => array(
              'class' => array('ed-discover-nodes-listing'),
            ),
            '#items' => $rows,
          );
          $form['result-listing']['pager'] = array(
            '#theme' => 'pager',
            '#weight' => 5,
          );
        }
      }
    }
  }

  return $form;
}

/**
 * Deals with dashboard discover page submit.
 * Redirects on op-search and saves a new search on
 * op-save-search button press.
 */
function ed_dashboard_discover_page_submit($form, &$form_state) {
  switch($form_state['triggering_element']['#name']) {
    case 'op-search':
      $form_state['redirect'] = 'dashboard/discover';
      if (!empty($form_state['input']['search_tag'])) {
        $form_state['redirect'] .= '/' . $form_state['input']['search_tag'];
      }
      break;
    case 'op-save-search':
      if (!empty($form_state['input']['search_tag'])) {
        $account = $GLOBALS['user'];
        db_insert('ed_user_tag_search')
          ->fields(array(
            'uid' => $account->uid,
            'tag' => truncate_utf8(strip_tags($form_state['input']['search_tag']), 128),
            'timestamp' => REQUEST_TIME,
          ))
          ->execute();
      }
      break;
    default:
      $form_state['rebuild'] = TRUE;
  }
}

/**
 * Returns ed_cluster node identifiers that current user is an active
 * member of.
 * Uses pager extender.
 */
function _ed_dashboard_get_current_user_groups() {
  $acc = $GLOBALS['user'];
  $query = db_select('node', 'n')
    ->extend('PagerDefault')
    ->limit(ed_get_paging_nr());
  $query->join('og_membership', 'ogm', "n.nid = ogm.gid AND ogm.entity_type = 'user' AND ogm.group_type = 'node' AND ogm.state = :active AND ogm.etid = :uid", array(':active' => OG_STATE_ACTIVE, ':uid' => $acc->uid));
  $query->fields('n', array('nid'))
    ->condition('n.type', 'ed_cluster')
    ->addTag('node_access');
  $query->orderBy('n.created','DESC');

  return $query->execute()->fetchCol();
}

/**
 * Implements hook_block_info().
 */
function ed_dashboard_block_info() {
  $blocks['ed_dashboard_saved_searches'] = array(
    'info' => t('Saved searches'),
    'status' => TRUE,
    'title' => '<none>',
    'region' => 'sidebar_second',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => "dashboard/discover\ndashboard/discover/*",
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ed_dashboard_block_view($block_name='') {
  if ('ed_dashboard_saved_searches' == $block_name) {
    $account = $GLOBALS['user'];

    $content['heading'] = array(
      '#type' => 'markup',
      '#prefix' => '<h2>',
      '#markup' => t('Saved searches'),
      '#suffix' => '</h2>',
    );

    $query = db_select('ed_user_tag_search', 'uts')
      ->fields('uts', array('sid', 'tag'))
      ->condition('uts.uid', $account->uid);

    $result = $query->execute()->fetchAll();

    if (!empty($result)) {
      // Not using #attached as it does not load translations
      drupal_add_js(drupal_get_path('module', 'ed_dashboard') . '/js/ed_dashboard_discover.js', 'file');
      foreach ($result as $key => $single) {
        $listing_items []= l('<i class="fa fa-times"></i>', '', array('attributes' => array('class' => array('ed-remove-search'), 'data-id' => $single->sid), 'html' => TRUE))
          . l($single->tag, 'dashboard/discover/' . $single->tag);
      }
      $content['searches-list'] = array(
        '#theme' => 'item_list',
        '#items' => $listing_items,
        '#attributes' => array(
          'class' => array('ed-saved-searches'),
        ),
        '#attached' => array(
          'css' => array(
            drupal_get_path('module', 'ed_dashboard') . '/css/ed_dashboard_discover.css'
          ),
        ),
      );
    }

    $block = array(
      'subject' => 'Saved searches',
      'content' => $content,
    );

    return $block;

  }
}

/**
 * Deals with ajax callback to delete a search.
 */
function ed_dashboard_delete_search($sid) {
  $response = array(
    'success' => false,
  );

  if (!$sid) {
    return drupal_json_output($response);
  }

  $account = $GLOBALS['user'];
  $num_deleted = db_delete('ed_user_tag_search')
    ->condition('sid', $sid)
    ->condition('uid', $account->uid)
    ->execute();

  if ($num_deleted) {
    $response['success'] = true;
  }

  return drupal_json_output($response);
}

/**
 * Implements hook_user_delete().
 */
function ed_dashboard_user_delete($account) {
  // Delete any discovery searches of the user
  db_delete('ed_user_tag_search')
    ->condition('uid', $account->uid)
    ->execute();
}

