<?php

/**
 * @file
 * eDidaktikum file module.
 */

/**
 * Implements hook_menu().
 */
function ed_file_menu() {
  $items['dashboard/files'] = array(
    'title' => t('Files'),
    'page callback' => 'ed_file_listing_page',
    'access callback' => 'user_is_logged_in',
    'weight' => 10,
    'menu_name' => 'ed-dashboard-menu',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function ed_file_menu_breadcrumb_alter(&$active_trail, $item) {
  //error_log("alter breadcrumb");

  //error_log(print_r($active_trail, true));
  /*$query_parameters = drupal_get_query_parameters();
  $folder = null;
  if (isset($query_parameters['folder'])) {
    $folder = $query_parameters['folder'];
  } 
  
  if (!drupal_is_front_page()) {
    $end = end($active_trail);
    if ($item['href'] == $end['href']) {
      $end['in_active_trail'] = false;
      $active_trail[] = $end;
    }
  }*/

  /*$active_trail []= array(
    'link_title' => 'kala',
  );*/

}

function ed_file_add_folder_to_breadcrumb($breadcrumb, $folder) {
  if ($folder->ed_file_folder_ref) {
    $folder_id = $folder->ed_file_folder_ref['und'][0]['target_id'];
    $folder = node_load($folder_id);
    $breadcrumb[] = l($folder->title, 'dashboard/files', array('query' => array('folder' => $folder->nid)));
    $breadcrumb = ed_file_add_folder_to_breadcrumb($breadcrumb, $folder);
  }
  return $breadcrumb;
}

/**
 * Files listing page.
 */
function ed_file_listing_page() {
  menu_tree_set_path('main-menu', 'dashboard');

  $query_parameters = drupal_get_query_parameters();
  $folder = null;
  if (isset($query_parameters['folder'])) {
    $folder_id = $query_parameters['folder'];
    $folder = node_load($folder_id);  
  } 
  $breadcrumb = drupal_get_breadcrumb();
  $url_parameters = array();
  if ($folder) { 
    $breadcrumb[] = l('Files', 'dashboard/files');
    $breadcrumb = ed_file_add_folder_to_breadcrumb($breadcrumb, $folder); 
    $breadcrumb[] = l($folder->title, 'dashboard/files', array('query' => array('folder' => $folder->nid)));
    drupal_set_breadcrumb($breadcrumb);
    $url_parameters = array('query' => array('ed_file_folder_ref' => $folder->nid));
  }
  
  $content = array();

  $add_file_url = l(t('file'), 'node/add/ed-file', $url_parameters);
  $add_file_folder_url = l(t('folder'), 'node/add/ed-file-folder', $url_parameters);
  $content['add-new'] = array(
    '#type' => 'markup',
    '#markup' => '<div>' . t('Add new ') . $add_file_url . t(' or ') . $add_file_folder_url . '</div>',
  );

  $header = array(
    array(
      'data' => '',
    ),
    array(
      'data' => t('Title'),
      'field' => 'n.title',
      'sort' => 'asc',
    ), 
    array(
      'data' => t('Type'),
    ),
    array(
      'data' => t('Changed'),
      'field' => 'n.changed',
      'sort' => 'desc',
    ),
    array(
      'data' => '',
    ),
  );


  $rows = array();
  //$files = node_load_multiple(ed_file_get_all_files());
  $files = ed_file_get_all_files_and_folders($header);
  foreach ($files as $file) {
    $file_type = ed_file_get_type($file);
    $icon_class = ed_file_get_icon_class($file_type);
    $file_url = l($file->title, 'node/' . $file->nid);
    if ($file->type == 'ed_file_folder') {
      $file_url = l($file->title, 'dashboard/files/', array('query' => array('folder' => $file->nid)));
    }
    $rows[] = array(
      'data' => array(
        'icon' => "<span class='ed-file-icon {$icon_class}'></span>",
        'title' => $file_url,
        'type' => $file_type,
        'changed' => format_date($file->changed, 'short'),
        'actions' => l(t('Edit'), 'node/' . $file->nid . '/edit'),
      ),
    );
  }
  if (!empty($rows)) {
    $content['table'] = array(
      '#theme' => 'table',
      '#attributes' => array(
        'class' => array('ed-files-table'),
      ),
      '#rows' => $rows,
      '#header' => $header,
    );
    $content['pager'] = array('#theme' => 'pager');
  }
  return $content;
}

function ed_file_get_type($node) {
  if ($node->type == 'ed_file_folder') {
    return "folder";
  } else if ($node->type == 'ed_file') {
    $nid = $node->nid;
    $full_node = node_load($nid);
    $file_upload_field = field_get_items('node', $full_node, 'ed_file_field_file_upload');
    $mimetype = $file_upload_field[0]['filemime'];
    return $mimetype; 
  }
  return "";
}

function ed_file_get_icon_class($mimetype) {
  if ($mimetype == 'text/plain') {
    return "ed-file-icon-txt";
  }
  return 'ed-file-icon-' . $mimetype;
}

/**
 * All files.
 */
function ed_file_get_all_files_and_folders($header) {

  $query_parameters = drupal_get_query_parameters();
  $folder_id = null;
  if (isset($query_parameters['folder'])) {
    $folder_id = $query_parameters['folder'];
  } 

  global $user;
  $query = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.type', array('ed_file', 'ed_file_folder'), 'in')
    ->condition('n.uid', $user->uid)
    ->addTag('node_access')
    ->range()
    ->extend('TableSort')
    ->extend('PagerDefault')->limit(10);  
  //->orderBy('n.created', 'DESC');

  $query->leftJoin('field_data_ed_file_folder_ref', 'folder', 'n.nid = folder.entity_id');
  $query->condition('folder.ed_file_folder_ref_target_id', $folder_id);
 
  $results = $query->fields('n', array('nid', 'title', 'type', 'changed'))->orderByHeader($header)->execute(); 
  return $results;
  $nids = $query->execute()->fetchCol();
  return $nids;
}

