<?php

require_once('ed_bookmark_functions.inc');
/*
 * Implements hook_node_info().
 */
function ed_bookmark_node_info() {
  $items['ed_bookmark'] = array(
    'name' => t('Bookmark'),
	  'type' => 'ed_bookmark',
	  'base' => 'node_content',
	  'description' => t('Description'),
	  'has_title' => '1',
	  'title_label' => t('Title'),	  
  );
  return $items;
}

/*
 * Implements hook_form().
 */
function ed_bookmark_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_form_alter().
 */
function ed_bookmark_form_alter(&$form, &$form_state, $form_id) {
  if ('ed_bookmark_node_form' == $form_id) {
    if (empty($form['#node']->nid)) {
      drupal_set_title(t('Create Bookmark'));
    }

    $form['title']['#required'] = FALSE;
    $form['ed_bookmark_url'][LANGUAGE_NONE][0]['#title'] = '';
  }
}

/**
 * Implements hook_node_presave().
 */
function ed_bookmark_node_presave($node) {
  if ('ed_bookmark' == $node->type) {
    // Use URL value if no title is provided
    $title = trim($node->title);
    if (empty($title)) {
      $node->title = $node->ed_bookmark_url[LANGUAGE_NONE][0]['value'];
    }
  }
}

