<?php

require_once('ed_bookmark_functions.inc');
/*
 * Implements hook_node_info().
 */
function ed_bookmark_node_info() {
  $items['ed_bookmark'] = array(
    'name' => t('Bookmark'),
	  'type' => 'ed_bookmark',
	  'base' => 'node_content',
	  'description' => t('Description'),
	  'has_title' => '1',
	  'title_label' => t('Title'),	  
  );
  return $items;
}

/*
 * Implements hook_form().
 */
function ed_bookmark_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_form_alter().
 */
function ed_bookmark_form_alter(&$form, &$form_state, $form_id) {
  if ('ed_bookmark_node_form' == $form_id) {
    if (empty($form['#node']->nid)) {
      drupal_set_title(t('Create Bookmark'));
    }

    $form['title']['#required'] = FALSE;
    $form['ed_bookmark_url'][LANGUAGE_NONE][0]['#title'] = '';
	
	  unset($form['ed_bookmark_type']);
  }
}

/**
 * Implements hook_node_presave().
 */
function ed_bookmark_node_presave($node) {
  if ('ed_bookmark' == $node->type) {
    // Use URL value if no title is provided
    $title = trim($node->title);
    if (empty($title)) {
      $node->title = $node->ed_bookmark_url[LANGUAGE_NONE][0]['value'];
    }
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function ed_bookmark_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => 1);
  }
}


/**
 * Implements hook_node_view().
 */
function ed_bookmark_node_view($node, $view_mode, $langcode){
  if($node->type == 'ed_bookmark'){
    if($view_mode == 'teaser'){    
      $node->content['ed_bookmark_type']['#label_display'] = 'hidden';
      $url = $node->ed_bookmark_url[LANGUAGE_NONE][0]['value'];
      $node->content['ed_bookmark_type'][0]['#markup'] = '';

      $node->content['ed_bookmark_description'][0]['#prefix'] = '<div class="description">';
      $node->content['ed_bookmark_description'][0]['#markup'] = l($url, $url) . '<br>' . $node->ed_bookmark_description[LANGUAGE_NONE][0]['value'] ;
      $node->content['ed_bookmark_description'][0]['#suffix'] = '</div>';
    }
  }
}
